### PR TITLE
Add GitHub Actions (CI) configuration

### LINKED ISSUE #2: Set up CI
We have some tests now (#1), so it's time to add CI and make sure this thing works not just on developer's machines.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #2.

@larswirzenius, is it okay for me to fetch your deb package from CI? It's just 2 megabytes right now, but it's done for every build, so might run into hundreds of megabytes if I'm tackling a problem that's only reproducible on CI servers. If it's not okay, I can probably cobble some cache together; just don't want to spend time on that if it's not necessary.

(And I do plan to copy 2d0add8 to Obnam, and mention it on the Subplot issue tracker too.)

### CODE REVIEW

**Comment by larswirzenius** [comment]
It's OK to fetch it from my CI APT repository.

**Comment by Minoru** [comment]
Awesome, thank you!

**Comment by Minoru** [comment]
> I do plan to copy 2d0add8 to Obnam

Obnam already [sleeps for three seconds](https://gitlab.com/larswirzenius/obnam/-/blob/e28c0947b8e46cb830737fdb3f7c5f3e5237aa02/subplot/daemon.py#L51-L52) after calling `daemonize`, so my fix is not needed.

> and mention it on the Subplot issue tracker too

As of right now, [Subplot's lib doesn't contain daemonize.py](https://gitlab.com/larswirzenius/subplot/-/tree/0c693b50186f391753b2e69c8daca473fa280b37/lib), so there's nothing to report the bug against. I'll just keep an eye on merge requests there, and point this out when/if daemonize.py is upstreamed.

**Comment by Minoru** [comment]
I missed it, but Subplot included daemon.py into its library, and https://gitlab.com/larswirzenius/subplot/-/commit/cf5a9d568c676c62267bcbc465b603ec20f05f0f implements the workaround I implemented here.

**Pull request merged**
